-- =============================================================================
-- Live Order — Full Supabase Schema (Postgres + Storage)
-- Run this in the Supabase SQL Editor (one shot, idempotent where possible)
-- =============================================================================

-- 0. Extensions
-- =============================================================================
create extension if not exists "pgcrypto";

-- 1. Users
-- =============================================================================
create table if not exists public.users (
  id            bigint generated by default as identity primary key,
  uid           text unique not null,
  username      text not null default '',
  name          text not null default '',
  email         text not null default '',
  role          text not null default 'client',
  image_url     text not null default '',
  rating        numeric(3,2) default 5.0,
  vehicle_type  text default '',
  vehicle_plate text default '',
  vehicle_capacity text default '',
  trips_count   int default 0,
  years_active  int default 1,
  about         text default '',
  reviews       jsonb default '[]'::jsonb,
  is_verified   boolean default false,
  verification_status text default 'unsubmitted',
  driver_status text default '',
  is_available  boolean default true,
  current_lat   numeric(10,7) default 30.0444,
  current_long  numeric(10,7) default 31.2357,
  national_id   text default '',
  license_number text default '',
  id_front_image  text default '',
  id_back_image   text default '',
  license_image   text default '',
  vehicle_image   text default '',
  created_at    timestamptz default now(),
  updated_at    timestamptz default now(),
  fcm_token     text default '',
  profile_image text default '',
  phone         text default '',
  address       text default '',
  is_deleted    boolean default false,
  deleted_at    timestamptz,
  notification_settings jsonb default '{}'::jsonb,
  reward_points int default 0
);

comment on table public.users is 'User profiles — clients, drivers, admins';

-- Indexes
create index if not exists idx_users_uid on public.users (uid);
create index if not exists idx_users_role on public.users (role);
create index if not exists idx_users_driver_status on public.users (driver_status);
create index if not exists idx_users_verification_status on public.users (verification_status);

-- 2. Orders (Shipments)
-- =============================================================================
create table if not exists public.orders (
  id                  text primary key,
  order_user_id       text not null default '',
  client_id           text not null default '',
  driver_id           text default '',
  order_name          text default 'شحنة بضائع',
  order_status        text default 'Waiting Driver',
  pickup_address      text default '',
  pickup_lat          numeric(10,7) default 0,
  pickup_lng          numeric(10,7) default 0,
  drop_address        text default '',
  drop_lat            numeric(10,7) default 0,
  drop_lng            numeric(10,7) default 0,
  order_size          text default 'M',
  weight              numeric(10,2) default 1.0,
  notes               text default '',
  images              jsonb default '[]'::jsonb,
  order_date          text default '',
  preferred_time_range text default '',
  price_estimate      numeric(10,2) default 0,
  payment_method      text default 'عند الاستلام',
  rating              numeric(3,2),
  review              text default '',
  total_price         numeric(10,2) default 0,
  assigned_driver     jsonb,
  created_at          timestamptz default now(),
  updated_at          timestamptz default now()
);

comment on table public.orders is 'Shipments / delivery orders';

create index if not exists idx_orders_user_id on public.orders (order_user_id);
create index if not exists idx_orders_driver_id on public.orders (driver_id);
create index if not exists idx_orders_status on public.orders (order_status);

-- 3. Chat Messages (driver chat)
-- =============================================================================
create table if not exists public.chat_messages (
  id          bigint generated by default as identity primary key,
  chat_id     text not null,
  sender_id   text not null,
  is_read     boolean default false,
  text        text default '',
  timestamp   timestamptz default now()
);

create index if not exists idx_chat_messages_chat_id on public.chat_messages (chat_id);

-- 4. Messages (user chat)
-- =============================================================================
create table if not exists public.messages (
  id              bigint generated by default as identity primary key,
  chat_id         text not null,
  sender_id       text not null default '',
  text            text default '',
  timestamp       timestamptz default now(),
  attachment_url  text default '',
  attachment_type text default '',
  latitude        numeric(10,7),
  longitude       numeric(10,7)
);

create index if not exists idx_messages_chat_id on public.messages (chat_id);

-- 5. Notifications
-- =============================================================================
create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  title       text default '',
  body        text default '',
  category    text default '',
  is_read     boolean default false,
  timestamp   timestamptz default now()
);

create index if not exists idx_notifications_user_id on public.notifications (user_id);

-- 6. Reviews (driver ratings)
-- =============================================================================
create table if not exists public.reviews (
  id          bigint generated by default as identity primary key,
  driver_id   text not null,
  rating      numeric(3,2) default 5.0
);

create index if not exists idx_reviews_driver_id on public.reviews (driver_id);

-- 7. Payment Cards
-- =============================================================================
create table if not exists public.cards (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  card_holder text default '',
  card_number text default '',
  expiry_date text default '',
  card_type   text default ''
);

create index if not exists idx_cards_user_id on public.cards (user_id);

-- 8. Transactions (payments)
-- =============================================================================
create table if not exists public.transactions (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  amount      numeric(10,2) default 0,
  title       text default '',
  status      text default '',
  category    text default '',
  timestamp   timestamptz default now()
);

create index if not exists idx_transactions_user_id on public.transactions (user_id);

-- 9. Reward Transactions
-- =============================================================================
create table if not exists public.reward_transactions (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  points      int default 0,
  title       text default '',
  type        text default '',
  timestamp   timestamptz default now()
);

create index if not exists idx_reward_tx_user_id on public.reward_transactions (user_id);

-- 10. Reports (user reports on drivers)
-- =============================================================================
create table if not exists public.reports (
  id          bigint generated by default as identity primary key,
  driver_id   text not null,
  driver_name text default '',
  reporter_id text default '',
  reason      text default '',
  timestamp   timestamptz default now()
);

-- 11. User Activity Log
-- =============================================================================
create table if not exists public.user_activity (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  activity    text default '',
  timestamp   timestamptz default now()
);

create index if not exists idx_user_activity_user_id on public.user_activity (user_id);

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================
alter table public.users enable row level security;
alter table public.orders enable row level security;
alter table public.chat_messages enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
alter table public.reviews enable row level security;
alter table public.cards enable row level security;
alter table public.transactions enable row level security;
alter table public.reward_transactions enable row level security;
alter table public.reports enable row level security;
alter table public.user_activity enable row level security;

-- ── users ────────────────────────────────────────────────────────────────────
create policy "users_select_own" on public.users
  for select using (uid = auth.uid()::text);
create policy "users_select_drivers" on public.users
  for select using (role = 'driver');
create policy "users_insert_own" on public.users
  for insert with check (uid = auth.uid()::text);
create policy "users_update_own" on public.users
  for update using (uid = auth.uid()::text);

-- ── orders ────────────────────────────────────────────────────────────────────
create policy "orders_select_own" on public.orders
  for select using (order_user_id = auth.uid()::text or driver_id = auth.uid()::text);
create policy "orders_insert_own" on public.orders
  for insert with check (order_user_id = auth.uid()::text);
create policy "orders_update_driver" on public.orders
  for update using (driver_id = auth.uid()::text);
create policy "orders_update_owner" on public.orders
  for update using (order_user_id = auth.uid()::text);

-- ── chat_messages ────────────────────────────────────────────────────────────
create policy "chat_messages_select_participant" on public.chat_messages
  for select using (true);
create policy "chat_messages_insert_participant" on public.chat_messages
  for insert with check (true);

-- ── messages ──────────────────────────────────────────────────────────────────
create policy "messages_select_participant" on public.messages
  for select using (true);
create policy "messages_insert_participant" on public.messages
  for insert with check (true);

-- ── notifications ────────────────────────────────────────────────────────────
create policy "notifications_select_own" on public.notifications
  for select using (user_id = auth.uid()::text);
create policy "notifications_update_own" on public.notifications
  for update using (user_id = auth.uid()::text);

-- ── reviews ──────────────────────────────────────────────────────────────────
create policy "reviews_all" on public.reviews
  for all using (true);

-- ── cards ────────────────────────────────────────────────────────────────────
create policy "cards_select_own" on public.cards
  for select using (user_id = auth.uid()::text);
create policy "cards_insert_own" on public.cards
  for insert with check (user_id = auth.uid()::text);
create policy "cards_delete_own" on public.cards
  for delete using (user_id = auth.uid()::text);

-- ── transactions ─────────────────────────────────────────────────────────────
create policy "transactions_select_own" on public.transactions
  for select using (user_id = auth.uid()::text);
create policy "transactions_insert_own" on public.transactions
  for insert with check (user_id = auth.uid()::text);

-- ── reward_transactions ──────────────────────────────────────────────────────
create policy "reward_tx_select_own" on public.reward_transactions
  for select using (user_id = auth.uid()::text);
create policy "reward_tx_insert_own" on public.reward_transactions
  for insert with check (user_id = auth.uid()::text);

-- ── reports ──────────────────────────────────────────────────────────────────
create policy "reports_insert_all" on public.reports
  for insert with check (true);

-- ── user_activity ────────────────────────────────────────────────────────────
create policy "user_activity_select_own" on public.user_activity
  for select using (user_id = auth.uid()::text);

-- =============================================================================
-- STORAGE — verification bucket
-- =============================================================================
insert into storage.buckets (id, name, public)
values ('verification', 'verification', true)
on conflict (id) do nothing;

-- Allow authenticated users to upload to verification bucket
create policy "verification_insert_own" on storage.objects
  for insert
  with check (
    bucket_id = 'verification'
    and auth.role() = 'authenticated'
  );

-- Allow public read of verification files
create policy "verification_select_public" on storage.objects
  for select
  using (bucket_id = 'verification');

-- =============================================================================
-- RPC — admin operations (bypass RLS via security definer)
-- =============================================================================
create or replace function public.admin_update_user_status(p_uid text, p_status text)
returns void
security definer
set search_path = public
language plpgsql as $$
begin
  update public.users set driver_status = p_status where uid = p_uid;
end;
$$;

-- =============================================================================
-- TRIGGERS — auto-update updated_at
-- =============================================================================
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'set_users_updated_at') then
    create trigger set_users_updated_at before update on public.users
      for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'set_orders_updated_at') then
    create trigger set_orders_updated_at before update on public.orders
      for each row execute function public.set_updated_at();
  end if;
end;
$$;

-- =============================================================================
-- REALTIME — enable streaming for tables that use .stream()
-- =============================================================================
-- In Supabase Dashboard: Replication → add tables to "supabase_realtime" publication
-- Or run:
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'users'
  ) then
    alter publication supabase_realtime add table public.users;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end;
$$;

-- =============================================================================
-- DONE
-- =============================================================================
